### ISSUE TITLE
Rebuild sendy php class

### ISSUE THREAD

**Issue by flowdee** [fdmedia-io/edd-sendy#11]
In addition to #7 , I thought that it would be the best to rebuild the Sendy PHP class completely. 

As mentioned, we're planning to create 1-2 more Sendy based plugins. So we can make use of this class in other plugins as well.

You can orientate on the convertkit api class you created lately.

**Comment by webdj-agency** [comment]
Done in [Rebuilt Sendy PHP class](https://github.com/fdmedia-io/edd-sendy/commit/23f89dc4cea0a181476dd776748986aadbd7f003) commit

**Comment by flowdee** [comment]
Could you please name the file: `fdmedia-sendy-api.php` and the class itself `FDMEDIA_Sendy_API` ?

**Comment by flowdee** [comment]
Released with v1.1
