### ISSUE TITLE
Pass "referrer" to API calls

### ISSUE THREAD

**Issue by flowdee** [fdmedia-io/edd-sendy#9]
I think we should pass `home_url()` by default here

<img width="984" alt="Bildschirmfoto 2020-06-26 um 10 06 59" src="https://user-images.githubusercontent.com/2278756/85835125-cff1e200-b794-11ea-9027-4c0975e27483.png">

**Comment by webdj-agency** [comment]
![referrer](https://user-images.githubusercontent.com/64838430/85931843-e486c500-b8cf-11ea-8cec-32e06c4564dc.png)

**Comment by flowdee** [comment]
Released with v1.1
